export const mockData = {
  board: {
    _id: "board-id-01",
    title: "TrungSon MERN Stack Board 123",
    description: "Pro MERN stack dev",
    type: "public", // 'private'
    ownerIds: [], // Những users là Admin của board
    memberIds: [], // Những users là member bình thường của board
    columnOrderIds: ["column-id-03", "column-id-01", "column-id-02"], // Thứ tự sắp xếp / vị trí của các Columns trong 1 boards
    columns: [
      {
        _id: "column-id-01",
        boardId: "board-id-01",
        title: "To Do",
        cardOrderIds: [
          "card-id-07",
          "card-id-02",
          "card-id-01",

          "card-id-03",
          "card-id-04",
          "card-id-05",
          "card-id-06",
        ],
        cards: [
          {
            _id: "card-id-01",
            boardId: "board-id-01",
            columnId: "column-id-01",
            title: "Say goodbye",
            description: "Say goodbye to my friends",
            cover:
              "https://th.bing.com/th/id/R.6f015e04e5174422b3d0251c4dca44b6?rik=Fz%2bRh%2fzt5RczNQ&pid=ImgRaw&r=0",
            memberIds: ["test-user-id-01"],
            comments: ["test comment 01", "test comment 02"],
            attachments: [
              "test attachment 01",
              "test attachment 02",
              "test attachment 03",
            ],
          },
          {
            _id: "card-id-02",
            boardId: "board-id-01",
            columnId: "card-id-01",
            title: "Assemble a team",
            description: null,
            cover:
              "https://scontent.fhan17-1.fna.fbcdn.net/v/t39.30808-6/398453455_708998997947441_2543813968004435393_n.jpg?stp=dst-jpg_s1080x2048&_nc_cat=108&ccb=1-7&_nc_sid=5f2048&_nc_ohc=oyceUrGZ6uQAX-yDyTc&_nc_ht=scontent.fhan17-1.fna&oh=00_AfCQavgjP3jT1_NoEU5kRxf0WbnlSqCFu2lVd4_fdp5l4A&oe=6560611D",
            memberIds: ["a"],
            comments: ["a"],
            attachments: ["c"],
          },
          {
            _id: "card-id-03",
            boardId: "board-id-01",
            columnId: "column-id-01",
            title: "Become God of Stories ",
            description: null,
            cover:
              "https://th.bing.com/th?id=OIF.YHYD%2fjIZOR5rb1Rk2%2fd7zA&rs=1&pid=ImgDetMain",
            memberIds: [1],
            comments: [2],
            attachments: [3],
          },
          // {
          //   _id: "card-id-04",
          //   boardId: "board-id-01",
          //   columnId: "column-id-01",
          //   title: "Title of card 04",
          //   description: null,
          //   cover: null,
          //   memberIds: [],
          //   comments: [],
          //   attachments: [],
          // },
          // {
          //   _id: "card-id-05",
          //   boardId: "board-id-01",
          //   columnId: "column-id-01",
          //   title: "Title of card 05",
          //   description: null,
          //   cover: null,
          //   memberIds: [],
          //   comments: [],
          //   attachments: [],
          // },
          // {
          //   _id: "card-id-06",
          //   boardId: "board-id-01",
          //   columnId: "column-id-01",
          //   title: "Title of card 06",
          //   description: null,
          //   cover: null,
          //   memberIds: [],
          //   comments: [],
          //   attachments: [],
          // },
          {
            _id: "card-id-07",
            boardId: "board-id-01",
            columnId: "column-id-01",
            title: "Talk to HWR after time slipping",
            description: null,
            cover:
              "https://th.bing.com/th/id/OIP.8w21YgbEDbLb0WH4KR9_eAHaEK?rs=1&pid=ImgDetMain",
            memberIds: [1],
            comments: [2],
            attachments: [3],
          },
        ],
      },
      {
        _id: "column-id-02",
        boardId: "board-id-01",
        title: "Inprogress ",
        cardOrderIds: ["card-id-08", "card-id-09", "card-id-10"],
        cards: [
          {
            _id: "card-id-08",
            boardId: "board-id-01",
            columnId: "column-id-02",
            title: "Find Sylvie",
            description: "Find Sylvie",
            cover: "https://i.ytimg.com/vi/FeuH0gWxX84/maxresdefault.jpg",
            memberIds: [1],
            comments: [2],
            attachments: [3],
          },
          {
            _id: "card-id-09",
            boardId: "board-id-01",
            columnId: "column-id-02",
            title: "Bring Timely to TVA",
            description: null,
            cover:
              "https://th.bing.com/th/id/OIP.n-Rk42ZeL4FsSj0DcndkewHaEK?w=1280&h=720&rs=1&pid=ImgDetMain",
            memberIds: [1],
            comments: [2],
            attachments: [3],
          },
          {
            _id: "card-id-10",
            boardId: "board-id-01",
            columnId: "column-id-02",
            title: "Tell OB to fix the Loom",
            description: null,
            cover:
              "https://th.bing.com/th/id/OIP.VMzZAcPIw3h6JXFEF8hRvAHaEK?rs=1&pid=ImgDetMain",
            memberIds: [1],
            comments: [2],
            attachments: [3],
          },
        ],
      },
      {
        _id: "column-id-03",
        boardId: "board-id-01",
        title: "Done ",
        cardOrderIds: ["card-id-11", "card-id-12", "card-id-13"],
        cards: [
          {
            _id: "card-id-11",
            boardId: "board-id-01",
            columnId: "column-id-03",
            title: "Meet Mobius",
            description: null,
            cover:
              "https://geekculture.co/wp-content/uploads/2021/06/loki-and-mobius-1200x800.jpeg",
            memberIds: [1],
            comments: [2],
            attachments: [3],
          },
          {
            _id: "card-id-12",
            boardId: "board-id-01",
            columnId: "column-id-03",
            title: "Fight Alioth",
            description: null,
            cover:
              "https://th.bing.com/th/id/OIP.Vp96Nxd5cCOaJl5o2NHSngHaDt?w=1400&h=700&rs=1&pid=ImgDetMain",
            memberIds: [1],
            comments: [2],
            attachments: [3],
          },
          {
            _id: "card-id-13",
            boardId: "board-id-01",
            columnId: "column-id-03",
            title: "Meet He Who Remains",
            description: null,
            cover:
              "https://www.disneydining.com/wp-content/uploads/2023/08/ret-invasion-1-1.jpg",
            memberIds: [1],
            comments: [2],
            attachments: [3],
          },
        ],
      },
    ],
  },
};
